#' Create a Column Definition for Death Counts
#'
#' @param maxWidth Maximum width of the column (default: 60)
#' @param class CSS class for the column (default: NULL)
#' @param maxValue Maximum value for scaling the background color (default: 100)
#' @param ... Additional arguments passed to colDef
#'
#' @return A column definition for use in reactable
#'
#' @keywords internal
deaths_column <- function(maxWidth = 60, class = NULL, maxValue = 100, ...) {
  colDef(
    maxWidth = maxWidth,
    defaultSortOrder = "desc",
    style = function(value) {
      # Lighter color for <1%
      if (is.na(value)){
        list(color = "#888", background="#fff")
      } else if (value / maxValue < 0.01) {
        list(color = "#888", background="#fff")
      } else {
        list(color = case_when(sqrt(value/ maxValue) < .4 ~ "#111",
                               TRUE ~ "#eee"),
             background = gray_pal(sqrt(value/ maxValue)),
             fontWeight = "bold")
      }
    },
    ...
  )
}

#' Display the Detailed Event Outcomes Table as an Interactive Reactable
#'
#' Creates an interactive table to display event, death total, and outcome
#' information. Columns counting deaths are group under a "deaths" heading.
#' Outcomes are color coded.
#'
#' @param dataset A data frame in the format generated by `wide_event_outcomes_table()`,
#'   possibly with extra columns added
#' @param static Logical, whether the table should be static or interactive (default: TRUE)
#' @param max_larger Numeric, allows setting a custom maximum value for death counts (default: 0)
#'
#' @return A reactable object displaying the event outcomes table
#'
#' @import dplyr
#' @import reactable
#'
#' @export
#'
#' @examples
#' deaths_aug24_filtered <- standard_filter(deaths_aug24)
#' deaths_aug24_unfiltered <- deaths_aug24
#' wetable <- wide_event_outcomes_table(deaths_aug24_filtered,
#'   deaths_aug24_unfiltered, event_status_aug24, drop_extra=TRUE, drop_separate=TRUE)
#' wide_event_outcomes_reactable(wetable)
wide_event_outcomes_reactable <- function(dataset, static=FALSE, max_larger=0) {
  deathcount.columns<- c("n","n_state_perp", "n_state_perp_hi",
                         "n_state_victim", "n_state_victim_hi",
                         "n_state_separate", "n_state_separate_hi",
                         "n_collateral", "n_nonconflict", "n_unconfirmed",
                         "n_unfiltered")

  numerical.columns <- deathcount.columns[which(deathcount.columns %in% colnames(dataset))]

  dataset <- dataset %>% relocate(any_of(numerical.columns), .before="outcome")

  # blank the high values if they are the same as the low values...
  dataset<- dataset %>%
    mutate(n_state_perp_hi = ifelse(n_state_perp_hi==n_state_perp, NA, n_state_perp_hi)) %>%
    mutate(n_state_victim_hi = ifelse(n_state_victim_hi==n_state_victim, NA, n_state_victim_hi))

  # alternate calculation of span
  max_deaths <- max(select(dataset, n:n_state_victim),  na.rm=TRUE)
  max_deaths <- max(max_deaths, max_larger) # allows the call to include a top value

  table <- reactable::reactable(dataset,
                                sortable=!static,
                                filterable=!static,
                                theme = nytimes(),
                                defaultPageSize=16,
                                pageSizeOptions = c(8, 16, 25, 35, 50),
                                showPageSizeOptions=TRUE,
                                defaultColDef = colDef(
                                  filterable=FALSE,
                                  defaultSortOrder = "desc",
                                  minWidth = 20, maxWidth=50),
                                columnGroups = list(colGroup(name = "deaths", columns = numerical.columns)),
                                columns = list (
                                  id = colDef(name="ID", maxWidth = 15),
                                  event_title = colDef (name="Event", minWidth=35, maxWidth=250,
                                                        defaultSortOrder = "asc",
                                                        filterable=!static,
                                                        style = list(fontWeight = "bold")),
                                  year = colDef (name="Year", maxWidth=50,
                                                 defaultSortOrder = "asc",
                                                 filterable=!static, sortNALast = TRUE,
                                                 style = list(background = "#ffffff")),
                                  protest_campaign = colDef (name="Campaign", minWidth=40, maxWidth=250,
                                                             defaultSortOrder = "asc",
                                                             filterable=!static,
                                                             style = list(fontWeight = "bold")),
                                  n = deaths_column(maxValue = max_deaths, name="Conf irmed"),
                                  n_state_perp = deaths_column(maxValue = max_deaths, name="State Perp"),
                                  n_state_perp_hi = colDef (name="\u2014", align = "left", format = colFormat(prefix = "\u2014 "),
                                                            minWidth = 15, maxWidth = 40),
                                  n_state_victim = deaths_column(maxValue = max_deaths, name="State Vict"),
                                  n_state_victim_hi = colDef (name="\u2014", align = "left", format = colFormat(prefix = "\u2014 "),
                                                              minWidth = 15, maxWidth = 40),
                                  n_state_separate = deaths_column(maxValue = max_deaths, name="Sep from State"),
                                  n_state_separate_hi = colDef (name="\u2014", align = "left", format = colFormat(prefix = "\u2014 "),
                                                                minWidth = 15, maxWidth = 40),
                                  n_collateral = colDef (name="Collateral",  defaultSortOrder = "desc"),
                                  n_nonconflict = colDef (name="Nonconflict", defaultSortOrder = "desc"),
                                  n_unconfirmed = colDef (name="Unconfirmed", defaultSortOrder = "desc"),
                                  outcome = colDef (name="Outcome", defaultSortOrder = "asc",  minWidth=40,
                                                    maxWidth = 90,
                                                    cell = function(value) {
                                                      badge <- switch(
                                                        value,
                                                        "Movement" = "\U25B2",
                                                        "State"= "\U25BC",
                                                        " "
                                                      )
                                                      str_c(badge, value, sep=" ")
                                                    },
                                                    style = function(value, index) {
                                                      if(is.na(dataset$outcome[index])){
                                                        list(color = "black")
                                                      }else if(dataset$outcome[index] == "Movement"){
                                                        list(color = "green")
                                                      }else if(dataset$outcome[index] == "State"){
                                                        list(color = "red")
                                                      }else if(dataset$outcome[index] == "None"){
                                                        list(color = "grey")
                                                      }
                                                    }
                                  ),
                                  outcome_summary = colDef (name="Outcome Summary", defaultSortOrder = "asc", minWidth=50, maxWidth = 140,
                                                            style = function(value, index) {
                                                              if(is.na(dataset$outcome[index])){

                                                              }else if(dataset$outcome[index] == "Movement"){
                                                                list(color="#000000", background = "#54AE32") #green
                                                              }else if(dataset$outcome[index] == "State"){
                                                                list(background = "#F2806F") # soft red
                                                              }else if(dataset$outcome[index] == "None"){
                                                                list(background = "#D5D5D5") # light gray
                                                              }
                                                            }),
                                  protest_domain = colDef (name="Protest Domain", minWidth=30,
                                                           defaultSortOrder = "asc",
                                                           filterable=!static,
                                                           maxWidth=120),
                                  pres_admin = colDef (name="President", minWidth=30,
                                                       defaultSortOrder = "asc",
                                                       filterable=!static, maxWidth=300)
                                )
  )
  return(table)
}


